language: node_js
node_js:
- "8.11.3"

matrix:
  fast_finish: true
  global:
    - env: PHPUNIT=global
  include:
    - php: 7.2
      env: PHPUNIT=local
    - php: 7.1
      env: PHPUNIT=local
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise
    - env: WP_VERSION=latest
    - env: WP_VERSION=4.5
    - env: WP_MULTISITE=1
    - language: node_js
      node_js:
       - "0.10"
  allow_failures:
    - env: WP_MULTISITE=1
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  except:
  - "/^*-v[0-9]/"

install:
  - if [[ $PHPUNIT = "local" ]]; then composer install; fi
  - chmod +x bin/init-grunt.sh
  - ". ./bin/init-grunt.sh"

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  - grunt
  - if [[ $PHPUNIT = "local" ]]; then ./vendor/bin/phpunit; else phpunit; fi

after_failure:
- cat "logs/phpcs.log"
- cat "logs/jslogs.log"